version: '3.8'

services:
    mariadb:
        image: mariadb:latest
        container_name: auto-pool-pump-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./docker/mariadb/init:/docker-entrypoint-initdb.d
        command: >
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
            --max_connections=1000

volumes:
    mariadb_data:
