services:
    db:
        image: mariadb:11
        restart: unless-stopped
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - '${MYSQL_PORT:-3307}:3306'
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test:
                [
                    'CMD',
                    'mysqladmin',
                    'ping',
                    '-h',
                    'localhost',
                    '-p${MYSQL_ROOT_PASSWORD}',
                ]
            interval: 5s
            timeout: 3s
            retries: 20
            start_period: 10s

volumes:
    db_data:
